HW_DIR := $(abspath $(CURDIR)/..)

TB_LIST := 

RTL_LIST := \
	src/system_top.v \
	src/top.v \
	src/timer.v \
	src/hex_conv.v \
	$(HW_DIR)/03_hex_display/src/display.v \
	$(HW_DIR)/03_hex_display/src/ctrl_74hc595.v \
	$(HW_DIR)/02_clkdiv/clkdiv.v \

include ../common/fpga.mk